---
# オフィシャルには以下のコマンド。これを展開してPlaybook化している。
#   curl https://mackerel.io/assets/files/scripts/setup-yum.sh | sh
#

- name: import mackerel GPG key
  rpm_key:
    key: https://mackerel.io/assets/files/GPG-KEY-mackerel
    state: present

- name: add repository 'mackerel'
  copy:
    src: _redhat/etc/yum.repos.d/mackerel.repo
    dest: /etc/yum.repos.d/mackerel.repo
    owner: root
    group: root
    mode: 0644

- name: install mackerel packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - mackerel-agent
    - mackerel-agent-plugins
    - mackerel-check-plugins
    - mkr
  register: install_mackerel

- service: name=mackerel-agent enabled=false
