---
- block:
    - get_url: url=https://amazon-ssm-ap-northeast-1.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm dest=/tmp/amazon-ssm-agent.rpm
    - yum: name=/tmp/amazon-ssm-agent.rpm state=installed
  when: ansible_distribution == 'Amazon'

- block:
    - get_url: url=https://amazon-ssm-ap-northeast-1.s3.amazonaws.com/latest/debian_amd64/amazon-ssm-agent.deb dest=/tmp/amazon-ssm-agent.deb
    - shell: dpkg -i /tmp/amazon-ssm-agent.deb
  when: ansible_distribution == 'Ubuntu'

- service: name=amazon-ssm-agent enabled=yes state=started
